version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Current Directory"
      - pwd
      - ls -la

  pre_build:
    commands:
      - echo "Java Version"
      - java -version
      - echo "Maven Version"
      - mvn -version

  build:
    commands:
      - echo "Project Structure"
      - cd BackEnd
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "Build Complete"
      - ls -ltr
      - ls -ltr target || true

artifacts:
  files:
    - BackEnd/target/*.jar
