spring.application.name=BackEnd

server.servlet.context-path=/api/v1

server.port=8083

# Database Configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/sys
# spring.datasource.username=root
# spring.datasource.password=rootuser@123

spring.datasource.url=jdbc:mysql://my-mysql-database.cpo8q48cgihy.us-east-2.rds.amazonaws.com:3306/my_application_db?sslMode=REQUIRED
spring.datasource.username=admin_user
spring.datasource.password=SuperSecurePassword123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

